package com.rngtech.rpg;

public enum MachinePartType {
    CRUSH_HEAD,
    HEAT_CORE,
    BIO_CHAMBER,
    ALLOY_CRUCIBLE,
    SERVO,
    FUEL_BOX,
    REACTOR_CHAMBER,
    RECOVERY_FILTER,
    CONTAINMENT_LINING,
    DISASSEMBLY_HEAD,
    FLUID_PUMP,
    CATHODE,
    REFORMING_CATALYST_BED,
    AMMONIA_CATALYST_BED,
    FUEL_CELL_MEMBRANE,
    CAVITATION_ROTOR,
    VOID_CHAMBER,
    COLLAPSE_NOZZLE,
    DIMENSIONAL_STABILIZER,
    SOLAR_ARRAY_EXTENDER,
    RESONANCE_COIL,
    CONTROL_BOARD,
    STABILIZER_MATRIX
}
